email:
  - username: your username@qq.com
    password: your password
  - username: 你的邮箱@gmail.com
    password: 你的密码
    pop_server: 邮箱的pop3服务地址，选填，默认取邮箱后缀

white_domain:
  - store.steampowered.com

bark_url: 
  - https://api.day.app/你的bark app的订阅地址/